proxy_cache_path /var/www/blockdust/.ipfs-cache levels=1:2 keys_zone=blockdust_ipfs:20m max_size=2g inactive=30d use_temp_path=off;
limit_req_zone $binary_remote_addr zone=blockdust_api_per_ip:10m rate=10r/s;
limit_req_zone $binary_remote_addr zone=blockdust_db_per_ip:10m rate=5r/s;
limit_req_zone $binary_remote_addr zone=blockdust_rpc_per_ip:10m rate=5r/s;
limit_req_zone $binary_remote_addr zone=blockdust_sync_per_ip:10m rate=1r/s;
limit_req_zone $binary_remote_addr zone=blockdust_media_per_ip:10m rate=10r/s;
